name: Outputs
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: danysk/action-checkout@0.1.0
      - id: branch-name # Custom id
        uses: tj-actions/branch-names@v5 # An action that has some outputs
      - run: |
          if ${{ steps.branch-name.outputs.is_tag }} ; then
            echo "This is tag ${{ steps.branch-name.outputs.tag }}
          else
            echo "This is branch ${{ steps.branch-name.outputs.current_branch }}
            echo "Is this branch the default one? ${{ steps.branch-name.outputs.is_default }}"
          fi
